
/**
 * common messages which used in app
 */
const commonStatement = {
   //Api Call Related Messages
   noNetworkAlert: "No Internet Connection.",
   requestTimeoutMessage: "It looks like the request is taking longer than expected time. Please check your internet connectivity and try again.",
   serverErrorMessage: "it looks like we're encountering server errors. We'll be back up soon. Sorry!",
   connectWithText: "Connect With",
   forgotPasswordText: "Forgot Password?",
   signUpText: "Sign Up",
   facebookKey: "FACEBOOOK",
   appleKey: "APPLE",
   googleKey: "GOOGLE",
   email: "Email",
   password: "Password",
   signupDOBMessage: "We need this information to help match you to your perfect partner. Over 18s only",
   whenoubornTitle: "When were you born?",
   selectDOBMessage: "You must be 18 years old or over.",
   addPhoto: "Add Photo",
   gif: "You can add only jpeg/png images",
   writeAnswerTitle: "Fact about me that Surprises people",
   photos: "Photos",
   enterVerificationCode: 'Enter your verification code',
   verificationDescMessage: "We just sent you a verification code",
   enterpasswordDescmessage: "Password with one capital alphabet, one small alphabet, one digit and one special character. Min 6 and Max 18 characters only",
   profileSetupMainPageText: "Profiles with personality, lead to better convos.",
   profileSetupUserNameDesc: "Start by giving us your name. As this is public, it doesn’t have to be your real name",
   profileSetupUserNameTitle: "What’s your name?",
   profileSetupUserProfesstionDesc: "This helps us connect you to relevant matches",
   profileSetupUserProfesstionTitle: "What do you do for a living?",
   profileSetupUserHeightDesc: "Tell us more about yourself to help us find you a partner who is perfect for you.",
   profileSetupUserheightTitle: "How tall are you?",
   profileSetupUserMaritalStatusDesc: "The more information you provide, allow us to match you with more relevant singles",
   profileSetupUserMaritalStatusTitle: "Your Marital Status",
   profileSetupUserChildrenDesc: "This helps us connect you to your ideal partner",
   profileSetupUserChildrenTitle: "Do you have children?",
   profileSetupUserCountryDesc: "Country where you work, eat, have fun and sleep",
   profileSetupUserCountryTitle: "Which country do you currently live in?",
   profileSetupUserPhoneTitle: "What's your Phone number?",
   profileSetupUserPhoneDesc: "You will receive an OTP on the phone number you enter below",
   profileSetupUserPhoneVerificationTitle: "Enter Verification Code",
   profileSetupUserPhoneVerificationDesc: "Please enter the code sent to your phone number via SMS",
   profileSetupUserCityDesc: "Name the place you let yourself be",
   profileSetupUserCityTitle: "What is the name of the city you live in?",
   profileSetupUserEthinicityDesc: "Where are your parents or grandparents originally from?",
   profileSetupUserEthinicityTitle: "What’s your ethnicity?",
   profileSetupUserCasteDesc: "Being spiritual is a fuel to your soul",
   profileSetupUserCasteTitle: "Your spirituality?",
   profileSetupUsermarriagegoalDesc: "Your idea about marriage can lead you to match with the one made for you",
   profileSetupUsermarriagegoalTitle: "What is your Marriage goal?",
   profileSetupUserEducationDesc: "Your ideal partner will not judge you by the degrees you hold, mentioning them would still be good.",
   profileSetupUserEducationTitle: "Degrees you hold",
   profileSetupUserProfileQuestionTitle: "Write your profile answers",
   profileSetupUserPrayDesc: "Your means of finding inner peace",
   nameText: "Name",
   city: "City",
   enterCityMessage: "Please enter your city",
   enterNameMessage: "Please enter your name",
   answerRequiredText: "5 answers required",
   phoneNumberplaceHolder: "Phone Number",
   enterEmailMessage: "Please enter email.",
   enterValidEmail: "Please enter valid email.",
   enterVerificationCodeMessage: "Please enter OTP.",
   enterValidOtpMessage: "The OTP entered is incorrect.",
   enterPasswordMessage: "Please enter Password.",
   enterConfirmPasswordMessage: "Please enter Confirm Password.",
   passwordSameMessage: "Password and confirm password doesn't match.",
   enterValidPwdMessage: "Password must be one capital alphabet, one small alphabet, one digit and one special character. Min 6 and Max 18 characters only.",
   genderSelectionMessage: "You’re creating a new account with the email",
   whatYourGender: "What is your gender?",
   selectOneDegreeMessage: "You have to select your degree",
   selectPromptTitle: 'Select a prompt',
   writeAnswerTitle: 'Write an answer',
   youAlreadySelectQuestion: "You have already selected this question",
   allQueAnsRequired: "Need the answers of all 5 questions",
   describeyourSelfAlert: "Please describe yourself",
   aboutSelfDesc: "In you own words, tell us more about yourself and what are you looking for.",
   aboutSelftitle: "How do you describe yourself?",
   pleaseSelectAllImage: "You have to upload 6 profile pictures, to complete the signup process",
   pleaseEnter6DigitPassword: "Password must contain at least minimum 6 characters.",
   pleaseEnterExistingPassword: "Please enter existing password.",
   pleaseEnterNewPassword: "Please enter New Password.",
   pleaseEnterConfirmNewPassword: "Please enter Confirm New Password.",
   passwordSameMessageForNewPassword: "New Password and Confirm New Password doesn't match.",
   noData: "No data found.",
   noMatchedUser: "New matches will appear here.",
   addaComment: "Add a comment",
   msgDeviceLocationPermission: 'Device Location is Not Enabled, Please Enable it from settings.',
   msgPermissionLocation: 'Please allow us to access your location.',
   somaliText: "Somali",
   mixedSomaliText: "Mixed Somali",
   nonSomaliText: "Non-Somali",
   marriagePrefrences: "Marriage preferences",
   abroadPrefrences: "Abroad preferences",
   selectBothPrefrence: "Please select Marriage and Abroad preferences",
   selectMarriagePref: "Please select Marriage preferences",
   selectAbroadPref: "Please select Abroad preferences",
   rightMinDescMessage: "Please describe yourself in minimum of 100 characters",
   signIn: "Sign In",
   submit: "Submit",
   continue: "Continue",
   exploreTitle: "Explore",
   messageUserText: "Message User",
   reportuserText: "Report User",
   blockUserText: "Block User",
   unblockUserText: "Unblock User",
   aboutMeText: "About me",
   likedyouText: "Liked you",
   passedText: "Passed",
   likedText: "Liked",
   blockedText: "Blocked",
   likesText: "Likes",
   ethnicity: "Ethnicity",
   staticTextFilterScreen: "Only see profile in discover matching these filters",
   blurPhoto: 'Blurred Photos',
   marriageGoal: "Marriage Goals",
   maritalStatus: "Marital Status",
   spirituality: "Spirituality",
   pray: "Pray",
   preferNotSay: "Prefer not to say",
   blurPhotoWarning: "We recommend un-blurring your photos to receive more matches.",
   reportUserreason1: "Inappropriate content",
   reportUserreason2: "Underage or minor",
   reportUserreason3: "Profile is fake",
   reportUserreason4: "Someone is in danger",
   selectReasonMessage: "Please select reason",
   noUserFoundMessage: "New messages will appear here.",
   typeMessagePlaceHolder: "Type a message",
   howYouFinduser: "How do you find this user?",
   serios: "Serious",
   polite: "Polite",
   recommended: "Recommended",
   noMoreProfileMessage: "No more profiles to show",
   nothaveAccount: "Don't have an account?",
   noMoreDataText: "You have seen everyone who matches your preferences, try other options.",
   pleaseEnterPhone: "Please enter your phone number",
   myAnswers: "My Answers",
   basicInfo: "Basic Info",
   moreAbout: "More About Me",
   aboutMe: "About Me",
   likedemptyMessage: "Profiles liked by you will be displayed here.",
   ignoredemptyMessage: "Profiles ignored by you will be displayed here.",
   blockedemptyMessage: "Profiles blocked by you will be displayed here.",
   likedYouemptyMessage: "Users who likes you will be displayed here.",
   emptySearchLikedMessage: "It seems that you have not liked anyone with your preference.",
   emptySearchIgnoredMessage: "It seems that you have not ignored anyone with your preference.",
   emptySearchBlockedMessage: "It seems that you have not blocked anyone with your preference.",
   emptySearchLikedYouMessage: "It seems that you don't have any likes from users with your preference.",
   subscriptionHeading: "Become a member,",
   subscriptionHeading2: "Cancel anytime",
   subscriptionSubHeading: "Preference by religion, profession, height, marital status and much more.",
   showAnyPlanAlert: "Please select a subscription plan.",
   restorePurchaseSucess: "Purchase restored successfully.",
   purchaseSucess: "You have subscribed sucessfully",
   restorePurchaseReceiptValidation: "Your subscription is seems like expired.",
   restorePurchaseNotFound: "No purchase found.",
   noNotificationFound: "Your preferred notifications will appear here.",

   hinduism: "Hinduism",
   buddhism: "Buddhism",
   Jainism: "Jainism",
   sikhism: "Sikhism",
   islam: "Islam",
   christianity: "Christianity",
   judaism: "Judaism",
   otherreligions: "Other religions",

   clearAllFilterMessageText: "Are you sure you want to clear all the filters?",

   selctProfilePicText: "Select Profile Picture",
   takePhotoText: "Take photo from Camera",
   chooseImageText: "Choose image",
   picFailedText: "Failed to load this image",
   loadingText: 'Loading...',
   typingText: "typing...",
   noDataText: "No data available",
   alreadyAssignText: "(Already assigned)",

   blockedMessage1: 'You are blocked by this user.',
   blockedMessage2: 'You have blocked this user.',
   blockedMessage3: 'You have blocked this user.',

   notSubscribedTextMessage: 'You are not a Subscribed user.',
   anyAgeText: "Any Age",
   openPrefrencesText: "Open Preferences",
   selectHeightText: 'Select Height',
   inInchesText: "in inches",
   limitByDiatnceText: "Limit By Distance",
   distanceMileText: "Distance ( Miles )",
   countryText: "Country",

   blurMyPhotoText: "Blur my photos",
   infoText: "Info",
   uploadingText: 'Uploading...',

   currentPlanText: "Current Plan",
   changePlanText: "Change Plan",
   freeText: " FREE",
   accountText: "Account",
   logOutText: "Logout",
   weekText: "Week",
   byContinueAgeText: 'By continuing you agree to our',
   andText: 'and',
   privacyPolicyText: 'Privacy Policy',

   networkErrorMessage: `Please retry after sometime.`,
   somethingWrongText: "Something went wrong",
   resetLinkMessage: "Please check your email,follow the link and reset your password.",
   netTitle: "Network Error",

   assignBadgeWaringText: "Please assign minimum one badge",
   profilePicWarning: "Profile photos allowed up to 8 MB.",
   unmatchWarningText: `You are no longer a match with this user and all your chat history with this user has been removed.`,

   subscriptionMessage1: "You have cancelled to subscirbe to this plan.",
   subscriptionMessage2: "You have already subscirbed to this plan.",
   subscriptionMessage3: 'Purchase Error',

   pleaseText: "Please",
   clearAllNotiText: "Are you sure you want to remove existing notifications from the list?",
   younolongerText: "You will no longer be matched with",
   andChatText: "and all your chat history with",
   willRemoveText: "will be removed. Are you sure you want to unmatch?",

   networkMessage: "Make sure your device is connected to the wifi or mobile data.",
   defaultFilterClearMessage: "You are not using any filters."
}

/**
 * routenames of each screen used in app
 */
const routeNames = {
   loginRoute: "LoginContainer",
   signUpRoute: "SignUpContainer",
   forgotPasswordRoute: "ForgotPasswordContainer",
   genderSelectionRoute: "GenderSelectionConatiner",
   signupDateOfBirthRoute: "SignUpDateOfBirthContainer",
   verificationRoute: "VerificationContainer",
   enterPasswordRoute: "EnterPasswordContainer",
   profileSetUpRoute: "ProfileSetupMainPage",
   descriptionProfileRoute: "DescriptionProfileContainer",
   termsAndPrivacyRoute: "CommonWebViewContainer",
   selectPromptRoute: "SelectPromptContainer",
   writeAnswerRoute: "WriteAnswerContainer",
   profilePicsRoute: "ProfilePicsContainer",
   profileSetupStepsRoute: "ProfileSetupStepsContainer",
   userNameRoute: "UserNameContainer",
   userProfessionRoute: "UserProfessionContainer",
   userHeightRoute: "UserHeightContainer",
   userMaritalStatusRoute: "UserMaritalStatusContainer",
   userChildrenRoute: "UserChildrenContainer",
   userCountryRoute: "UserCountryContainer",
   userCityRoute: "UserCityContainer",
   userEthnicityRoute: "UserEthnicityContainer",
   userSectRoute: "UserSectContainer",
   userPrayRoute: "UserPrayContainer",
   userMarriageGoalRoute: "UserMarriageGoalContainer",
   userDegreesRoute: "UserDegreesContainer",
   userProfileAnswersRoute: "UserProfileAnswersContainer",
   userPhoneNumberRoute: "UserPhoneNumberContainer",
   userPhoneVerificationRoute: "UserPhoneVerificationContainer",
   exploreRoute: 'ExploreContainer',
   likeRoute: 'LikeContainer',
   chatRoute: 'ChatContainer',
   settingsRoute: 'SettingContainer',
   changePasswordRoute: 'ChangePasswordContainer',
   likeCommentRoute: 'LikeCommentContainer',
   filterRoute: 'FilterContainer',
   ageSliderRoute: 'AgeSliderContainer',
   locationRoute: "LocationContainer",
   filterProfessionRoute: "FilterProfessionContainer",
   filterEducationRoute: "FilterEducationContainer",
   filterHeightRoute: "FilterHeightContainer",
   filtermarriageGoalRoute: "FilterMarriageGoalContainer",
   chatWindowRoute: "ChatWindowContainer",
   zoomImageRoute: "ZoomableImage",
   settingsScreenRoute: "SettingsScreenConatiner",
   noticationsRoute: "NoticationsContainer",
   matchesRoute: "MatchesContainer",
   editProfileRoute: "EditProfileContainer",
   userProfileRoute: "UserProfileContainer",
}

/**
 * page title which used in Header of Perticular screen
 */
const pageTitles = {
   forgotPassword: "Forgot Password",
   signUp: 'Sign Up',
   verification: "Verification",
   enterPassword: "Enter Password",
   profileSetUp: "Profile Setup",
   terms: "Terms & Conditions",
   privacyPolicy: "Privacy Policy",
   selectPrompt: "Select Prompt",
   writeAnswer: "Write Answer",
   resetPassword: "Reset Password",
   changePassword: "Change Password",
   filter: "Filters",
   age: "Age",
   location: "Location",
   profession: "Profession",
   education: "Education",
   height: "Height",
   chat: "Chat",
   settings: "Settings",
   notifications: "Notifications",
   matches: "Matches",
   editProfile: "Edit Profile"

}

/**
 * Common Button title
 */
const buttons = {
   submit: 'Submit',
   male: 'Male',
   female: 'Female',
   resend: 'Resend',
   getStarted: 'Get Started',
   continue: 'Continue',
   done: 'Done',
   single: 'Single',
   widowed: "Widowed",
   divorced: 'Divorced',
   yes: 'Yes',
   no: 'No',
   other: "Other",
   sunni: "Sunni",
   shia: "Shia",
   marriageOption1: "Seeking marriage within 1-2 years",
   marriageOption2: "Seeking marriage as soon as possible",
   marriageOption3: "Will move abroad",
   marriageOption4: "Not willing to move abroad",
   search: "Search",
   logout: "Logout",
   cancel: "Cancel",
   sendLike: "Send Like",
   upgradeToUnlock: "Upgrade to Unlock",
   SubscriptionPlan: 'Subscription Plan',
   veryReligious: "Very Religious",
   religious: "Religious",
   notveryreligious: "Not very religious",
   GetFreeTrial: 'Get Free Trial',
   alwayspray: "I always pray",
   usuallypray: "I usually pray",
   sometimespray: "I sometimes pray",
   liketostart: "I don't pray, but would like to start",
   preferNotSay: "Prefer not to say",
   getFree: "Get Free Trial",
   getThreeMonths: "Get 3 Months Subscription",
   getTwelveMonths: "Get 12 Months Subscription",
   subscribe: "Subscribe",
   restorePurchase: "Restore Purchase",
   cancelSubscription: "Cancel Subscription",
   switchplan: "Switch Plan",
   unmatchUser: "Unmatch User",
   confirm: "Confirm",
   okay: "Okay"
}

/**
 * set of all messages and text
 */
const commonText = {
   ...routeNames,
   ...commonStatement,
   ...pageTitles,
   ...buttons,
}

export default commonText;