/**action types for login module */
export const loginActionTypes = {
   LOGIN_REQUEST: "LOGIN_REQUEST",
   LOGIN_FAILURE: "LOGIN_FAILURE",
   LOGIN_SUCCESS: "LOGIN_SUCCESS",
   LOGIN_RESET_DATA: "LOGIN_RESET_DATA",
}

/**action types for signup module */
export const signupActionTypes = {
   SIGNUP_REQUEST: "SIGNUP_REQUEST",
   SIGNUP_FAILURE: "SIGNUP_FAILURE",
   SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
   SIGNUP_RESET_DATA: "SIGNUP_RESET_DATA",
}

/**action types for profile setup module */
export const profileSetupActionTypes = {
   PROFILESETUP_REQUEST: "PROFILESETUP_REQUEST",
   PROFILESETUP_FAILURE: "PROFILESETUP_FAILURE",
   PROFILESETUP_SUCCESS: "PROFILESETUP_SUCCESS",
   PROFILSETUP_RESET_DATA: "PROFILSETUP_RESET_DATA",
   PROFILESETUP_INCREASE_INDEX: "PROFILESETUP_INCREASE_INDEX",
   PROFILESETUP_DECREASE_INDEX: "PROFILESETUP_DECREASE_INDEX",
   PROFILESETUP_INCREASE_EDIT_INDEX: "PROFILESETUP_INCREASE_EDIT_INDEX",
   PROFILESETUP_GET_PROFESSTION_SUCCESS: "PROFILESETUP_GET_PROFESSTION_SUCCESS",
   PROFILESETUP_GET_ETHNICITY_SUCCESS: "PROFILESETUP_GET_ETHNICITY_SUCCESS",
   PROFILESETUP_GET_CASTS_SUCCESS: "PROFILESETUP_GET_CASTS_SUCCESS",
   PROFILESETUP_GET_EDUCATION_SUCCESS: "PROFILESETUP_GET_EDUCATION_SUCCESS",
   PROFILESETUP_ADD_EDUCATION_DEGREE: "PROFILESETUP_ADD_EDUCATION_DEGREE",
   PROFILESETUP_REMOVE_EDUCATION_DEGREE: "PROFILESETUP_REMOVE_EDUCATION_DEGREE",
   PROFILESETUP_GET_QUEANS_ARRAY_LIST: "PROFILESETUP_GET_QUEANS_ARRAY_LIST",
   PROFILESETUP_GET_USER_PROFILE_DETAILS: "PROFILESETUP_GET_USER_PROFILE_DETAILS",
   PROFILE_SETUP_GET_PROMPT_QUE_SUCCESS: "PROFILE_SETUP_GET_PROMPT_QUE_SUCCESS",
   PROFESSION_INDEX: "PROFESSION_INDEX"
}

/**action types for forgot password module */
export const forgotPasswordActionTypes = {
   FORGOT_PASSWORD_REQUEST: "FORGOT_PASSWORD_REQUEST",
   FORGOT_PASSWORD_FAILURE: "FORGOT_PASSWORD_FAILURE",
   FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS",
   FORGOT_PASSWORD_RESET_DATA: "FORGOT_PASSWORD_RESET_DATA",
}

/**action types for user profile module */
export const userProfileActionTypes = {
   USER_PROFILE_REQUEST: "USER_PROFILE_REQUEST",
   USER_PROFILE_SUCCESS: "USER_PROFILE_SUCCESS",
   USER_PROFILE_FAILURE: "USER_PROFILE_FAILURE",
   USER_PROFILE_GET_PROFILE_DATA: "USER_PROFILE_GET_PROFILE_DATA",
   USER_PROFILE_RESET_DATA: "USER_PROFILE_RESET_DATA",
}

/**action types for Explore module */
export const exploreActionTypes = {
   EXPLORE_REQUEST: "EXPLORE_REQUEST",
   EXPLORE_SUCCESS: "EXPLORE_SUCCESS",
   EXPLORE_FAILURE: "EXPLORE_FAILURE",
   EXPLORE_LOAD_USER_DATA: "EXPLORE_LOAD_USER_DATA",
   EXPLORE_RESET_DATA: "EXPLORE_RESET_DATA",
   EXPLORE_SET_NO_PROFILE_FOUND: "EXPLORE_SET_NO_PROFILE_FOUND",
   EXPLORE_SET_BLANK_DATA: "EXPLORE_SET_BLANK_DATA",
   EXPLORE_LOAD_USER_LIST_FROM_BACKEND: "EXPLORE_LOAD_USER_LIST_FROM_BACKEND",
   EXPLORE_REDUCE_USER_LIST: 'EXPLORE_REDUCE_USER_LIST',
   EXPLORE_RESET_USER_LIST: "EXPLORE_RESET_USER_LIST",
   EXPLORE_SET_NO_MORE_DATA: "EXPLORE_SET_NO_MORE_DATA",
   EXPLORE_LOAD_USER_PROFILE_DATA: "EXPLORE_LOAD_USER_PROFILE_DATA",
}

/**action types for filter module */
export const filterActionTypes = {
   FILTER_REQEST: "FILTER_REQEST",
   FILTER_SUCCESS: "FILTER_SUCCESS",
   FILTER_FAILURE: "FILTER_FAILURE",
   FILTER_RESET_DATA: "FILTER_RESET_DATA",
   FILTER_LOAD_PROFFESTION_DATA: "FILTER_LOAD_PROFFESTION_DATA",
   FILTER_ADD_PROFFESTION_DATA: "FILTER_ADD_PROFFESTION_DATA",
   FILTER_REMOVE_PROFFESTION_DATA: "FILTER_REMOVE_PROFFESTION_DATA",
   FILTER_LOAD_EDUCATION_DATA: "FILTER_LOAD_EDUCATION_DATA",
   FILTER_ADD_EDUCATION_DATA: "FILTER_ADD_EDUCATION_DATA",
   FILTER_REMOVE_EDUCATION_DATA: "FILTER_REMOVE_EDUCATION_DATA",
   FILTER_CHANGE_ANY_AGE_TOGGLE_VALUE: "FILTER_CHANGE_ANY_AGE_TOGGLE_VALUE",
   FILTER_SET_MIN_MAX_AGE_VALUE: "FILTER_SET_MIN_MAX_AGE_VALUE",
   FILTER_CHANGE_LOCATION_SELECTED_INDEX: "FILTER_CHANGE_LOCATION_SELECTED_INDEX",
   FILTER_LOCATION_SET_MIN_MAX_LOCATION_DISTANCE: "FILTER_LOCATION_SET_MIN_MAX_LOCATION_DISTANCE",
   FILTER_LOCATION_ADD_COUNTRY_TO_LIST: "FILTER_LOCATION_ADD_COUNTRY_TO_LIST",
   FILTER_LOCATION_REMOVE_COUNTRY_FROM_LIST: "FILTER_LOCATION_REMOVE_COUNTRY_FROM_LIST",
   FILTER_TOGGLE_BLUR_PHOTO: "FILTER_TOGGLE_BLUR_PHOTO",
   FILTER_ADD_MODAL_VALUE_TO_SPECIFIC_LIST: "FILTER_ADD_MODAL_VALUE_TO_SPECIFIC_LIST",
   FILTER_REMOVE_MODAL_VALUE_FROM_SPECIFIC_LIST: "FILTER_REMOVE_MODAL_VALUE_FROM_SPECIFIC_LIST",
   FILTER_HEIGHT_SET_MIN_MAX_VALUE: "FILTER_HEIGHT_SET_MIN_MAX_VALUE",
   FILTER_GET_ARRAY_LIST: "FILTER_GET_ARRAY_LIST",
   FILTER_STORE_DATA: "FILTER_STORE_DATA",
}

/**action types for Like module */
export const likeActionTypes = {
   LIKE_REQUEST: "LIKE_REQUEST",
   LIKE_FAILURE: "LIKE_FAILURE",
   LIKE_SUCCESS: "LIKE_SUCCESS",
   LIKE_RESET_DATA: "LIKE_RESET_DATA",
   LIKE_LOAD_DATA: "LIKE_LOAD_DATA",
   LIKE_CHANGE_SELECTED_TAB_INDEX: "LIKE_CHANGE_SELECTED_TAB_INDEX",
   LIKE_LOAD_USER_LIST_DATA: "LIKE_LOAD_USER_LIST_DATA",
   LIKE_SET_SEARCHED_VALUE: "LIKE_SET_SEARCHED_VALUE",
   LIKE_RESET_SPECIFIC_TAB_LIST: "LIKE_RESET_SPECIFIC_TAB_LIST",
}

/**action types for Chat module */
export const chatActionTypes = {
   CHAT_REQUEST: "CHAT_REQUEST",
   CHAT_FAILURE: "CHAT_FAILURE",
   CHAT_SUCCESS: "CHAT_SUCCESS",
   CHAT_RESET_DATA: "CHAT_RESET_DATA",
   CHAT_LOAD_USER_LIST: "CHAT_LOAD_USER_LIST",
   CHAT_LOAD_USER_CHAT_MESSAGE_LIST: "CHAT_LOAD_USER_CHAT_MESSAGE_LIST",
   CHAT_SET_SEARCHED_VALUE: "CHAT_SET_SEARCHED_VALUE",
   CHAT_RESET_MESSAGES: "CHAT_RESET_MESSAGES",
   CHAT_SET_MESSAGES: "CHAT_SET_MESSAGES",
   CHAT_GET_OLD_MESSAGES: "CHAT_GET_OLD_MESSAGES",
   CHAT_GET_NEW_MESSAGE: "CHAT_GET_NEW_MESSAGE",
   CHAT_ADD_BADGE_TO_LIST: "CHAT_ADD_BADGE_TO_LIST",
   CHAT_REMOVE_BADGE_FROM_LIST: "CHAT_REMOVE_BADGE_FROM_LIST",
   RESET_CHAT_BADGE_LIST: "RESET_CHAT_BADGE_LIST",

}

/**action types for match user module */
export const matchedUsersActionTypes = {
   MATCHED_USERS_REQUEST: "MATCHED_USERS_REQUEST",
   MATCHED_USERS_FAILURE: "MATCHED_USERS_FAILURE",
   MATCHED_USERS_SUCCESS: "MATCHED_USERS_SUCCESS",
   MATCHED_USERS_RESET_DATA: "MATCHED_USERS_RESET_DATA",
}

/**action types for notification module */
export const notificationActionTypes = {
   NOTIFICATION_REQUEST: "NOTIFICATION_REQUEST",
   NOTIFICATION_FAILURE: "NOTIFICATION_FAILURE",
   NOTIFICATION_SUCCESS: "NOTIFICATION_SUCCESS",
   NOTIFICATION_DATA_SUCCESS: "NOTIFICATION_DATA_SUCCESS",
   NOTIFICATION_RESET_DATA: "NOTIFICATION_RESET_DATA",
   NOTIFICATION_LOAD_MORE_REQUEST: "NOTIFICATION_LOAD_MORE_REQUEST",
   NOTIFICATION_LOAD_MORE_FAILURE: "NOTIFICATION_LOAD_MORE_FAILURE",
}

/**action types for notification permission module */
export const notificationPermissionActionTypes = {
   NOTIFICATION_PERMISSION_REQUEST: "NOTIFICATION_PERMISSION_REQUEST",
   NOTIFICATION_PERMISSION_FAILURE: "NOTIFICATION_PERMISSION_FAILURE",
   NOTIFICATION_PERMISSION_SUCCESS: "NOTIFICATION_PERMISSION_SUCCESS",
}

/**action types for subscripion module */
export const subscribtionActionTypes = {
   SUBSCRIBTION_REQUEST: "SUBSCRIBTION_REQUEST",
   SUBSCRIBTION_SUCCESS: "SUBSCRIBTION_SUCCESS",
   SUBSCRIBTION_FAILURE: "SUBSCRIBTION_FAILURE",
   SUBSCRIBTION_LOAD_PRODUCT_LIST: "SUBSCRIBTION_LOAD_PRODUCT_LIST",
   SUBSCRIBTION_RESET_DATA: "SUBSCRIBTION_RESET_DATA",
   SUBSCRIBTION_LOAD_IAP_PRDUCT_LIST: "SUBSCRIBTION_LOAD_IAP_PRDUCT_LIST",
   SUBSCRIBTION_STORE_SELECTED_PLAN_DETAILS: "SUBSCRIBTION_STORE_SELECTED_PLAN_DETAILS",
   SUBSCRIBTION_SELECT_PLAN_INDEX: "SUBSCRIBTION_SELECT_PLAN_INDEX",
}